# Generated by Django 5.0.4 on 2024-06-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obesystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='weightage',
            field=models.FloatField(default=0, help_text='Max weightage varies by assessment type.'),
        ),
    ]
