# Generated by Django 5.0.4 on 2024-06-09 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obesystem', '0002_alter_customuser_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='director',
        ),
    ]
