# Generated by Django 5.0.4 on 2024-06-12 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obesystem', '0002_assessment_weightage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='total_marks',
        ),
        migrations.AddField(
            model_name='question',
            name='weightage',
            field=models.FloatField(default=0, help_text='Maximum weightage is 10.'),
        ),
    ]
