# Generated by Django 5.0.4 on 2024-06-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obesystem', '0003_remove_department_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='total_marks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.IntegerField(),
        ),
    ]
