# Generated by Django 5.0.4 on 2024-08-31 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obesystem', '0004_courselearningoutcome_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='department',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('faculty', 'Faculty Member'), ('student', 'Student')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='program',
            name='hod',
            field=models.ForeignKey(limit_choices_to={'role': 'faculty'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_heads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
