# Generated by Django 5.0.4 on 2024-08-31 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obesystem', '0006_rename_code_course_course_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='section',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='student',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
