# Generated by Django 5.0.4 on 2024-09-02 02:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obesystem', '0008_section_batch_section_section_section_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programlearningoutcome',
            name='name',
        ),
        migrations.AddField(
            model_name='programlearningoutcome',
            name='PLO',
            field=models.PositiveIntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programlearningoutcome',
            name='heading',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
