# Generated by Django 5.0.4 on 2024-09-02 03:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obesystem', '0010_alter_programlearningoutcome_plo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselearningoutcome',
            name='name',
        ),
        migrations.AddField(
            model_name='courselearningoutcome',
            name='CLO',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15')], default=1, unique=True, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='courselearningoutcome',
            name='related_plo',
        ),
        migrations.AddField(
            model_name='courselearningoutcome',
            name='related_plo',
            field=models.ManyToManyField(related_name='related_clos', to='obesystem.programlearningoutcome'),
        ),
    ]
