# Generated by Django 5.0.4 on 2024-09-02 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obesystem', '0011_remove_courselearningoutcome_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courselearningoutcome',
            old_name='related_plo',
            new_name='mapped_to_PLO',
        ),
    ]
