# Generated by Django 5.0.4 on 2024-09-12 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obesystem', '0012_rename_related_plo_courselearningoutcome_mapped_to_plo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courselearningoutcome',
            name='CLO',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15')], validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='courselearningoutcome',
            constraint=models.UniqueConstraint(fields=('course', 'CLO'), name='unique_clo_per_course'),
        ),
    ]
