# Generated by Django 5.0.4 on 2024-09-14 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obesystem', '0013_alter_courselearningoutcome_clo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='weightage',
        ),
        migrations.AddField(
            model_name='assessment',
            name='marks',
            field=models.FloatField(default=0, help_text='Enter the total marks for the assessment.', validators=[django.core.validators.MinValueValidator(0.0)]),
            preserve_default=False,
        ),
    ]
