# Generated by Django 5.0.4 on 2024-09-14 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obesystem', '0014_remove_assessment_weightage_assessment_marks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='clo',
        ),
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.IntegerField(help_text='Marks must be a positive integer.', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='question',
            name='clo',
            field=models.ManyToManyField(related_name='questions', to='obesystem.courselearningoutcome'),
        ),
    ]
