# Generated by Django 5.0.4 on 2024-09-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obesystem', '0015_remove_question_clo_alter_question_marks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='weightage',
        ),
    ]
