# Generated by Django 5.0.4 on 2024-11-02 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obesystem', '0019_alter_programlearningoutcome_plo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramCLOMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weightage', models.FloatField()),
                ('clo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_mappings', to='obesystem.courselearningoutcome')),
                ('plo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clo_mappings', to='obesystem.programlearningoutcome')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clo_mappings', to='obesystem.program')),
            ],
            options={
                'unique_together': {('program', 'clo', 'plo')},
            },
        ),
    ]
