# Generated by Django 5.0.4 on 2024-11-02 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obesystem', '0020_programclomapping'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programclomapping',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='programclomapping',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='program_clo_mappings', to='obesystem.course'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='programclomapping',
            unique_together={('program', 'course', 'clo', 'plo')},
        ),
    ]
