# Generated by Django 5.0.4 on 2024-11-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obesystem', '0021_alter_programclomapping_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_id', 'name', 'credit_hours')},
        ),
        migrations.AddField(
            model_name='course',
            name='programs',
            field=models.ManyToManyField(related_name='courses', to='obesystem.program'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=10),
        ),
        migrations.RemoveField(
            model_name='course',
            name='program',
        ),
    ]
