# Generated by Django 5.0.4 on 2024-11-05 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obesystem', '0023_section_program_section_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselearningoutcome',
            name='mapped_to_PLO',
        ),
        migrations.RemoveField(
            model_name='courselearningoutcome',
            name='weightage',
        ),
        migrations.AddField(
            model_name='courselearningoutcome',
            name='heading',
            field=models.CharField(default='Heading', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='programlearningoutcome',
            name='weightage',
            field=models.FloatField(help_text='PLO weightage must be between 0.0 and 100.0', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
