# Generated by Django 5.0.4 on 2024-11-09 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obesystem', '0024_remove_courselearningoutcome_mapped_to_plo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_weightage', models.PositiveIntegerField(default=0)),
                ('quiz_weightage', models.PositiveIntegerField(default=0)),
                ('lab_weightage', models.PositiveIntegerField(default=0)),
                ('mid_weightage', models.PositiveIntegerField(default=0)),
                ('final_weightage', models.PositiveIntegerField(default=0)),
                ('project_weightage', models.PositiveIntegerField(default=0)),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='obesystem.section')),
            ],
            options={
                'verbose_name': 'Assessment Breakdown',
                'verbose_name_plural': 'Assessment Breakdowns',
            },
        ),
    ]
