# Generated by Django 5.0.4 on 2024-11-18 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obesystem', '0025_assessmentbreakdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programclomapping',
            name='clo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='program_mapping', to='obesystem.courselearningoutcome'),
        ),
    ]
