# Generated by Django 5.0.4 on 2024-11-18 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obesystem', '0026_alter_programclomapping_clo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='programclomapping',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='programclomapping',
            name='clo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_mappings', to='obesystem.courselearningoutcome'),
        ),
        migrations.AlterUniqueTogether(
            name='programclomapping',
            unique_together={('program', 'course', 'clo')},
        ),
    ]
