# Generated by Django 5.0.4 on 2024-11-20 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obesystem', '0027_alter_programclomapping_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courselearningoutcome',
            name='weightage',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
