# Generated by Django 5.0.4 on 2024-11-27 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obesystem', '0029_remove_assessment_marks_assessment_weightage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='clo',
            field=models.ManyToManyField(blank=True, related_name='questions', to='obesystem.courselearningoutcome'),
        ),
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.FloatField(help_text='Marks must be a positive number.', validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
