# Generated by Django 5.0.4 on 2024-11-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obesystem', '0030_remove_question_text_question_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='clo',
            field=models.ManyToManyField(help_text='At least one CLO must be mapped to this question.', related_name='questions', to='obesystem.courselearningoutcome'),
        ),
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
