# Generated by Django 5.0.4 on 2024-11-29 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obesystem', '0032_remove_question_number_alter_assessment_weightage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'permissions': [('can_add_assessment', 'Can add assessment to this section')]},
        ),
    ]
