# Generated by Django 5.0.4 on 2024-12-08 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obesystem', '0035_studentquestionscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentquestionscore',
            name='marks_obtained',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
