# Generated by Django 5.0.4 on 2024-12-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obesystem', '0036_alter_studentquestionscore_marks_obtained'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='program_type',
            field=models.CharField(choices=[('UG', 'Undergraduate'), ('GR', 'Graduate'), ('PG', 'Postgraduate')], default='UG', max_length=2),
            preserve_default=False,
        ),
    ]
