# Generated by Django 5.0.4 on 2024-12-16 11:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('quiz', 'Quiz'), ('assignment', 'Assignment'), ('midterm', 'Midterm'), ('final', 'Final Exam'), ('lab', 'Lab'), ('project', 'Project')], max_length=20)),
                ('weightage', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
            ],
            options={
                'permissions': [('can_add_question', 'Can add question to this assessment')],
            },
        ),
        migrations.CreateModel(
            name='AssessmentBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_weightage', models.PositiveIntegerField(default=0)),
                ('quiz_weightage', models.PositiveIntegerField(default=0)),
                ('lab_weightage', models.PositiveIntegerField(default=0)),
                ('mid_weightage', models.PositiveIntegerField(default=0)),
                ('final_weightage', models.PositiveIntegerField(default=0)),
                ('project_weightage', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Assessment Breakdown',
                'verbose_name_plural': 'Assessment Breakdowns',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.FloatField(help_text='Marks must be a positive number.', validators=[django.core.validators.MinValueValidator(0.1)])),
            ],
        ),
        migrations.CreateModel(
            name='StudentQuestionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks_obtained', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
    ]
