# Generated by Django 5.0.4 on 2024-12-16 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('outcomes', '0002_initial'),
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='sections.section'),
        ),
        migrations.AddField(
            model_name='assessmentbreakdown',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sections.section'),
        ),
        migrations.AddField(
            model_name='question',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='question',
            name='clo',
            field=models.ManyToManyField(help_text='At least one CLO must be mapped to this question.', related_name='questions', to='outcomes.courselearningoutcome'),
        ),
        migrations.AddField(
            model_name='studentquestionscore',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.question'),
        ),
    ]
