# Generated by Django 5.0.4 on 2025-02-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentbreakdown',
            name='assignment_weightage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='assessmentbreakdown',
            name='final_weightage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='assessmentbreakdown',
            name='lab_weightage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='assessmentbreakdown',
            name='mid_weightage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='assessmentbreakdown',
            name='project_weightage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='assessmentbreakdown',
            name='quiz_weightage',
            field=models.FloatField(default=0),
        ),
    ]
