# Generated by Django 5.0.4 on 2025-02-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_alter_assessmentbreakdown_assignment_weightage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentquestionscore',
            name='marks_obtained',
            field=models.FloatField(),
        ),
    ]
