# Generated by Django 5.0.4 on 2024-04-28 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=255, unique=True)),
                ('course_name', models.CharField(max_length=255, unique=True)),
                ('credit_hrs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PLO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PLO_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_code', models.CharField(max_length=255, unique=True)),
                ('program_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CLO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLO_details', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OBE.course')),
                ('plo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OBE.plo')),
            ],
        ),
        migrations.AddField(
            model_name='plo',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OBE.program'),
        ),
        migrations.AddField(
            model_name='course',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OBE.program'),
        ),
    ]
