from .student_clo_atainment import CLOAttainmentAPI
from .user_section_api import StudentSectionsAPI
from .faculty_clo_attainment import FacultyCLOAttainment
from .faculty_section_list import FacultySectionsList
from .student_final_result import StudentFinalResultAPI
from .faculty_final_result import FacultyFinalResultsAPI