# Generated by Django 5.0.4 on 2024-12-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='programs',
            field=models.ManyToManyField(related_name='courses', to='programs.program'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course_id', 'name', 'credit_hours')},
        ),
    ]
