# Generated by Django 5.0.4 on 2024-12-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
