# Generated by Django 5.0.4 on 2025-01-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='year',
            field=models.CharField(choices=[('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034')], max_length=4),
        ),
    ]
