# Generated by Django 5.0.4 on 2026-03-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_alter_section_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='year',
            field=models.CharField(choices=[('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034'), ('2035', '2035')], max_length=4),
        ),
    ]
