# Generated by Django 5.0.4 on 2024-12-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='hod',
            new_name='program_incharge',
        ),
        migrations.RemoveField(
            model_name='program',
            name='name',
        ),
        migrations.AddField(
            model_name='program',
            name='program_abbreviation',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='program_title',
            field=models.CharField(default='BSCS', max_length=100),
            preserve_default=False,
        ),
    ]
