# Generated by Django 5.0.4 on 2024-12-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_rename_hod_program_program_incharge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_abbreviation',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
