# Generated by Django 5.0.4 on 2025-01-08 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_alter_program_program_abbreviation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_incharge',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'faculty'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_heads', to=settings.AUTH_USER_MODEL),
        ),
    ]
