from .assessment_admin import *
from .course_admin import *
from .course_learning_outcome_admin import *
from .custom_user_admin import *
from .program_admin import *
from .program_clo_mapping_admin import *
from .program_learning_outcome_admin import *
from .question_admin import *
from .section_admin import *